****************************************************************																																
*   THIS FILE IS GENERATED BY THE SCREEN PAINTER.              *																																
*   NEVER CHANGE IT MANUALLY, PLEASE !                         *																																
****************************************************************																																
%_DYNPRO																																
ZNOTES_TZ_SCREENS																																
0300																																
752																																
             40																																
%_HEADER																																
ZNOTES_TZ_SCREENS                       0300 0300     22 87192 37  0  0 27120  0G E                              20231020040120																																
%_DESCRIPTION																																
creating note																																
%_FIELDS																																
LABEL_CREATE	0	CHAR	 16	00	00	00	30	00	  2	 48		  0	  0	  0		  0					  0	  0								Создание_заметки		
CREATE_TITLE	0	CHAR	 24	00	00	00	30	00	  4	 45		  0	  0	  0		  0					  0	  0								Введите_название_заметки		
INPUT_TITLE	C	CHAR	 28	80	06	A8	00	00	  5	 43		  0	  0	  0		  0			INPUT_TITLE		  0	  0								?___________________________		
CREATE_TEXT	0	CHAR	 21	00	00	00	30	00	  6	 46		  0	  0	  0		  0					  0	  0								Введите_текст_заметки		
INPUT_TEXT			 64	00	00	00	30	00	  7	 25		  0	  0	  0		 12	U				  1	  1	101									
BUTTON_CREATE		CHAR	 29	00	00	00	30	00	 20	 43		  0	  0	  0		  0	P				  0	  0	102							Создать______________________	                                                                                                                                                                        NEW	
BUTTON_BACK		CHAR	 29	00	00	00	30	00	 22	 43		  0	  0	  0		  0	P				  0	  0	103							Назад________________________	                                                                                                                                                                        BACK	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
  MODULE status_0300.																																
*																																
PROCESS AFTER INPUT.																																
  MODULE user_command_0300.																																
%_PARAMS																																
																																
