****************************************************************																																
*   THIS FILE IS GENERATED BY THE SCREEN PAINTER.              *																																
*   NEVER CHANGE IT MANUALLY, PLEASE !                         *																																
****************************************************************																																
%_DYNPRO																																
ZNOTES_TZ_SCREENS																																
0101																																
752																																
             40																																
%_HEADER																																
ZNOTES_TZ_SCREENS                       0101 0101     17 77192 37  0  0 27120  0G E                              20231020180747																																
%_DESCRIPTION																																
menu																																
%_FIELDS																																
WELCOME_TEXT	0	CHAR	 20	00	00	00	30	00	  6	 46		  0	  0	  0		  0					  0	  0								Приложение_"Заметки"		
CHOOSE_TEXT	0	CHAR	 16	00	00	00	30	00	  8	 48		  0	  0	  0		  0					  0	  0								Выберите_заметку		
LIST_LAB	C	CHAR	 41	80	04	08	00	00	  9	 36		  0	  0	  0		 43			LIST_LAB		  0	  0								_________________________________________	 DL	
BUTTON_EDIT		CHAR	 18	00	00	00	30	00	 11	 47		  0	  0	  0		  0	P				  0	  0	101							Редактировать_____	                                                                                                                                                                        EDIT	
BUTTON_DELETE		CHAR	 18	00	00	00	30	00	 13	 47		  0	  0	  0		  0	P				  0	  0	102							Удалить___________	                                                                                                                                                                        DEL	
RNEW		CHAR	 18	00	00	00	30	00	 15	 47		  0	  0	  0		  0	P				  0	  0	103							Создать_новую_____	                                                                                                                                                                        NEW	
BUTTON_EXIT		CHAR	 18	00	00	00	30	00	 17	 47		  0	  0	  0		  0	P				  0	  0	104							Закрыть_приложение	                                                                                                                                                                        EXIT	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
  MODULE status_0101.																																
																																
PROCESS AFTER INPUT.																																
  MODULE user_command_0101.																																
%_PARAMS																																
																																
