****************************************************************																																
*   THIS FILE IS GENERATED BY THE SCREEN PAINTER.              *																																
*   NEVER CHANGE IT MANUALLY, PLEASE !                         *																																
****************************************************************																																
%_DYNPRO																																
ZNOTES_TZ_SCREENS																																
0200																																
752																																
             40																																
%_HEADER																																
ZNOTES_TZ_SCREENS                       0200 0200     23 84192 37  0  0 27120  0G E                              20231020040239																																
%_DESCRIPTION																																
output screen																																
%_FIELDS																																
VIEW_LABEL	0	CHAR	  8	00	00	00	30	00	  5	 53		  0	  0	  0		  0					  0	  0								########		
VIEW_TITLE	C	CHAR	 31	80	02	A8	00	00	  6	 42		  0	  0	  0		  0					  0	  0								?______________________________		
VIEW_TEXT			 57	00	00	00	30	00	  8	 29		  0	  0	  0		 12	U				  1	  1	101									
BUTTNON_SAVE		CHAR	 25	00	00	00	30	00	 21	 45		  0	  0	  0		  0	P				  0	  0	102							#########________________	                                                                                                                                                                        SAVE	
VIEW_BACK		CHAR	 25	00	00	00	30	00	 23	 45		  0	  0	  0		  0	P				  0	  0	103							#####____________________	                                                                                                                                                                        BACK	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
  MODULE status_0200.																																
*																																
PROCESS AFTER INPUT.																																
  MODULE user_command_0200.																																
%_PARAMS																																
																																
